# Site settings
title: derickson.github.io
description: The Full Stack tech explorations of Dave Erickson.
baseurl: "" # the subpath of your site, e.g. /blog/
##url: "http://www.front2backdev.com" # the base hostname & protocol for your site
##url: "http://localhost:4000" # the base hostname & protocol for your site
url: "http://derickson.github.io/" # the base hostname & protocol for your site
twitter_username: davebenigno
github_username:  derickson

paginate: 10

# Build settings
markdown: kramdown
